name: AWS Continuous Deployment workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        working-directory: ./foodfinder-frontend
        run: npm install
      - name: Run npm build
        working-directory: ./foodfinder-frontend
        run: npm run build --if-present
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./foodfinder-frontend/dist

  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_BUCKET_NAME : ${{ secrets.AWS_BUCKET_NAME }}
      AWS_REGION : ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN : ${{ secrets.AWS_ROLE_ARN }}

    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: dist
          path: ./foodfinder-frontend/dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: $AWS_ROLE_ARN
          role-session-name: deploymentsession
          aws-region: $AWS_REGION

      # Upload a file to AWS S3
      - name: Copy dist to S3
        run: |
          aws s3 cp ./foodfinder-frontend/dist s3://$AWS_BUCKET_NAME/
